FROM golang:1.12-alpine
RUN apk add --no-cache git
WORKDIR /src/konfplate
COPY konfplate.go .
RUN go get -d -v && CGO_ENABLED=0 GOOS=linux go build -a konfplate.go

FROM alpine:3.9
COPY --from=0 /src/konfplate/konfplate .
ENTRYPOINT [ "./konfplate" ]
CMD [ "--help" ]